src/menus/urls.py
from django.conf.urls import url

from .views import (
	ItemCreateView,
	ItemDetailView,
	ItemListView,
	ItemUpdateView,
)


urlpatterns = [
    url(r'^$', ItemListView.as_view(), name='list'),
    url(r'^create/$', ItemCreateView.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/update/$', ItemUpdateView.as_view(), name='update'),
    url(r'^(?P<pk>\d+)/$', ItemDetailView.as_view(), name='detail'),
]

src/muypicky/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

from django.contrib.auth.views import LoginView

from restaurants.views import (
	RestaurantListView,
	RestaurantDetailView,
    RestaurantCreateView,
)


urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^items/', include('menus.urls', namespace='menus')),
    url(r'^restaurants/', include('restaurants.urls', namespace='restaurants')),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^contact/$', TemplateView.as_view(template_name='about.html'), name='contact'),
]

src/restaurants/urls.py
from django.conf.urls import url

from restaurants.views import (
	RestaurantListView,
	RestaurantDetailView,
    RestaurantCreateView,
    RestaurantUpdateView,
)


urlpatterns = [
    url(r'^$', RestaurantListView.as_view(), name='list'),
    url(r'^create/$', RestaurantCreateView.as_view(), name='create'),
    url(r'^(?P<slug>[-\w]+)/edit/$', RestaurantUpdateView.as_view(), name='edit'),
    url(r'^(?P<slug>[-\w]+)/$', RestaurantDetailView.as_view(), name='detail'),
]

src/menus/models.py
from django.conf import settings
from django.db import models
from django.core.urlresolvers import reverse

from restaurants.models import RestaurantLocation

class Item(models.Model):
	# associations
	user 		= models.ForeignKey(settings.AUTH_USER_MODEL)
	restaurant 	= models.ForeignKey(RestaurantLocation)

	#item stuff
	name 		= models.CharField(max_length=120)
	contents 	= models.TextField(help_text='separe each item by comma')
	excludes 	= models.TextField(blank=True, null=True, help_text='separe each item by comma')
	public 		= models.BooleanField(default=True)
	timestamp 	= models.DateTimeField(auto_now_add=True)
	updated 	= models.DateTimeField(auto_now=True)
	

	def get_absolute_url(self):
		return reverse('menus:detail', kwargs={'pk': self.pk})

	class Meta:
		ordering = ['-updated', '-timestamp']

	def get_contents(self):
		return self.contents.split(",")

	def get_excludes(self):
		return self.excludes.split(",")

src/restaurants/models.py
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save, post_save
from django.core.urlresolvers import reverse

from .utils import unique_slug_generator
from .validators import validate_country

User = settings.AUTH_USER_MODEL

class RestaurantLocation(models.Model):
	BBK, JAPA, MEXICAN = 'ch', 'jp', 'mx'
	CATEGORY= (
		(BBK, 'Churrascaria'),
		(JAPA, 'Comida Japonesa'),
		(MEXICAN, 'Comida Mexicana'),
	)

	user 		= models.ForeignKey(User)
	name 		= models.CharField(max_length=120)
	country		= models.CharField(max_length=120, null=True, blank=True)
	location 	= models.CharField(max_length=120, null=True, blank=True)
	category 	= models.CharField(max_length=60, choices=CATEGORY, default=BBK)
	timestamp 	= models.DateTimeField(auto_now_add=True)
	updated 	= models.DateTimeField(auto_now=True)
	slug		= models.SlugField(null=True, blank=True)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('restaurants:detail', kwargs={'slug': self.slug})

	@property
	def title(self):
		return self.name

def rl_pre_save_receiver(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = unique_slug_generator(instance)

# def rl_post_save_receiver(sender, instance, created, *args, **kwargs):
# 	print('saved!')
# 	print(instance.timestamp)
# 	if not instance.slug:
# 		instance.slug = unique_slug_generator(instance)
# 		instance.save()

pre_save.connect(rl_pre_save_receiver, sender=RestaurantLocation)

# post_save.connect(rl_post_save_receiver, sender=RestaurantLocation)

src/menus/forms.py
from django import forms

from restaurants.models import RestaurantLocation

from .models import Item

class ItemForm(forms.ModelForm):
	class Meta:
		model = Item
		fields = [
		'restaurant',
		'contents',
		'excludes',
		'public'
		]

	def __init__(self, user=None, *args, **kwargs):
		super(ItemForm, self).__init__(*args, **kwargs)
		self.fields['restaurant'].queryset = RestaurantLocation.objects.filter(user=user)

src/restaurants/forms.py
from django import forms

from .models import RestaurantLocation
from .validators import validate_country


class RestaurantLocationCreateForm(forms.ModelForm):
	COUNTRY = forms.CharField(required=False, validators=[validate_country])
	
	class Meta:
		model = RestaurantLocation
		fields = [
			'name',
			'location',
			'category',
		]

src/menus/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView

from .forms import ItemForm
from .models import Item


class ItemListView(ListView):

	def get_queryset(self):
		return Item.objects.all()


class ItemDetailView(DetailView):

	def get_queryset(self):
		return Item.objects.filter(user=self.request.user)
		

class ItemCreateView(LoginRequiredMixin, CreateView):
	template_name = 'form.html'
	form_class = ItemForm
	login_url = '/login/'

	def form_valid(self, form):
		obj = form.save(commit=False)
		obj.user = self.request.user
		return super(ItemCreateView, self).form_valid(form)

	def get_form_kwargs(self):
		kwargs = super(ItemCreateView, self).get_form_kwargs()
		kwargs['user'] = self.request.user
		return kwargs

	def get_queryset(self):
		return Item.objects.filter(user=self.request.user)
		
	def get_context_data(self, *args, **kwargs):
		context = super(ItemCreateView, self).get_context_data(*args, **kwargs)
		context['title'] = 'Create Item'
		return context


class ItemUpdateView(LoginRequiredMixin, UpdateView):
	template_name='form.html'
	form_class = ItemForm

	def get_queryset(self):
		return Item.objects.filter(user=self.request.user)

	def get_context_data(self, *args, **kwargs):
		context = super(ItemUpdateView, self).get_context_data(*args, **kwargs)
		context['title'] = 'Update Item'
		return context

	def get_form_kwargs(self):
		kwargs = super(ItemUpdateView, self).get_form_kwargs()
		kwargs['user'] = self.request.user
		return kwargs

src/restaurants/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views import View
from django.views.generic import (
	TemplateView,
	ListView,
	DetailView,
	CreateView,
	UpdateView,
)
from .forms import RestaurantLocationCreateForm
from .models import RestaurantLocation


class RestaurantListView(ListView):
	template_name = 'restaurants/restaurants_list.html'

	def get_queryset(self):
		return RestaurantLocation.objects.filter(user=self.request.user)



class RestaurantDetailView(DetailView):
	template_name = 'restaurants/restaurants_detail.html'

	def get_queryset(self):
		return RestaurantLocation.objects.filter(user=self.request.user)



class RestaurantCreateView(LoginRequiredMixin, CreateView):
	form_class = RestaurantLocationCreateForm
	login_url = '/login/'
	template_name = 'form.html'
	# success_url = '/restaurants/'
	
	def form_valid(self, form):
		instance = form.save(commit=False)
		instance.user = self.request.user
		return super(RestaurantCreateView, self).form_valid(form)

	def get_context_data(self, *args, **kwargs):
		context = super(RestaurantCreateView, self).get_context_data(*args, **kwargs)
		context['title'] = 'Add Restaurant'
		return context


class RestaurantUpdateView(LoginRequiredMixin, CreateView):
	form_class = RestaurantLocationCreateForm
	template_name = 'form.html'
	
	def get_context_data(self, *args, **kwargs):
		context = super(RestaurantUpdateView, self).get_context_data(*args, **kwargs)
		context['title'] = 'Edit Restaurant'
		return context

	def get_queryset(self):
		return RestaurantLocation.objects.filter(user=self.request.user)	

src/menus/templates/menus/item_detail.html
{% extends "base.html" %}

{% block head_title %} Menu items | {{ block.super }} {% endblock head_title %}

{% block content %}
<h1>{{ object.name }}</h1>
<p>Location: {{ object.restaurant.name }}</p>

{% if object.contents %}
Contents
<ul>
	{% for item in object.get_contents %}
	<li>{{ item }}</li>
	{% endfor %}
</ul>
{% endif %}

{% if object.excludes %}
Excludes
<ul>
	{% for item in object.get_excludes %}
	<li>{{ item }}</li>
			{% endfor %}
</ul>
{% endif %}

{% endblock %}

src/menus/templates/menus/item_list.html
{% extends "base.html" %}

{% block head_title %} Menu items | {{ block.super }} {% endblock head_title %}

{% block content %}
<h1>Menu Items</h1>

<ul>
{%  for obj in object_list %}
	<li> <a href='{{ obj.get_absolute_url }}'>{{ obj.name }}</a><br/>
		{% if obj.contents %}
		Contents
		<ul>
			{% for item in obj.get_contents %}
			<li>{{ item }}</li>
			{% endfor %}
		</ul>
		{% endif %}

		{% if obj.excludes %}
		Excludes
		<ul>
			{% for item in obj.get_excludes %}
			<li>{{ item }}</li>
			{% endfor %}
		</ul>
		{% endif %}
	</li>
{% endfor %}
</ul>

{% endblock %}

src/restaurants/templates/restaurants/form.html
{% extends "base.html" %}

{% block head_title %}Add Restaurant | {{ block.super }}{% endblock head_title %}

{% block content %}
<h1>Add Restaurant</h1>

{% if form.errors %}
{{ form.errors }}
{% endif %}
<form method='POST'> {% csrf_token %}
		{{ form.as_p }}
		<button type='submit'>Save</button>
</form>

{% endblock %}

src/restaurants/templates/restaurants/restaurants_detail.html
{% extends "base.html" %}

{% block head_title %} Restaurants | {{ block.super }} {% endblock head_title %}

{% block content %}
<h1>{{ object.title }}<small> {{ object.category }}</small> </h1>
<p>{{ object.location }}</p>
<p> {{ object.timestamp }}</p>
{% endblock %}

src/restaurants/templates/restaurants/restaurants_list.html
{% extends "base.html" %}

{% block head_title %} Restaurants | {{ block.super }} {% endblock head_title %}

{% block content %}
<h1>My Restaurant List<small><a href='{% url "restaurants:create" %}'>Add</a></small></h1>

<ul>
{%  for obj in object_list %}
	<li> <a href='{{ obj.get_absolute_url }}'>{{ obj }}</a><br/>
		{{ obj.name }}  {{ obj.location }}  {{ obj.timestamp }}
	</li>

{% empty %}
	<li><a href='{% url "restaurants:create" %}'>Add One</a></li>

{% endfor %}
</ul>

{% endblock %}

src/templates/about.html
{% extends 'base.html' %}
{% block head_title %}About || {{ block.super}} {% endblock head_title %}

{% block content %}

<h1>About</h1>

{% include 'snippets/sidebar.html' %}

{% endblock %}

src/templates/base.html
<!DOCTYPE html>
<html lang=en>

<head>
<title>{% block head_title %} MuyPicky.com{% endblock head_title %}</title>
{% include 'snippets/css.html' %}
</head>
<body>
{% include 'snippets/nav.html' %}

<div class='container'>
{% block content %}{% endblock content %}
</div>

</body>
</html>

src/templates/contact.html
{% extends 'base.html' %}
{% block head_title %}Contact || {{ block.super}} {% endblock head_title %}

{% block content %}

<h1>Contact</h1>

{% endblock %}

src/templates/form.html
{% extends "base.html" %}

{% block head_title %}{{ title }} | {{ block.super }}{% endblock head_title %}

{% block content %}
<h1>{{ title }}</h1>

{% if form.errors.non_field_errors %}
{{ form.errors.non_field_errors }}
{% endif %}
<form method='POST'> {% csrf_token %}
		{{ form.as_p }}
		<button type='submit'>Save</button>
</form>

{% endblock %}

src/templates/home.html
{% extends 'base.html' %}

{% block content %}

<h1>Home</h1>

<p>Home do projeto</p>

{% endblock %}

src/templates/snippets/css.html
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

src/templates/snippets/js.html
<script src=https://code.jquery.com/jquery-3.3.1.min.js"></script>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

src/templates/snippets/nav.html
<div class="container">
<h1>MuyPicky.com</h1>
<a href = '{% url "home" %}'> Home </a>
<a href='{% url "about" %}'>About</a>
<a href='{% url "restaurants:list" %}'>Restaurants</a>
<a href='{% url "contact" %}'>Contact</a>
<a href='{% url "menus:list" %}'>Menu Items</a>
</div>

src/templates/snippets/sidebar.html
<ul>
<li>Item 1</li>
<li>Item 2</li>
<li>Item 3</li>
</ul>